language: python
services:
  - memcached
cache:
  directories:
   - eggs
   - downloads
   - buildout-cache
python: 2.7
services:
  - xvfb
install:
  - mkdir -p buildout-cache/downloads
  - pip install -r requirements.txt
  - buildout -c travis.cfg -N
before_script:
  - export DISPLAY=:99.0
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
script: bin/test
notifications:
  email:
    recipients:
      - devel@lists.affinitic.be
      - devs@imio.be
    on_success: change
    on_failure: change
